### ISSUE TITLE
error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by razzbee** [azazel75/metapensiero.pj#14]
Installing using pip gives error : error: Unable to find vcvarsall.bat

Detailed : 
pip install javascripthon
Collecting javascripthon
  Using cached javascripthon-0.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\users\dr_success\appdata\local\programs\python\python35\lib\site-packages (from javascripthon)
Collecting dukpy (from javascripthon)
  Using cached dukpy-0.0.4.tar.gz
Installing collected packages: dukpy, javascripthon
  Running setup.py install for dukpy ... error
    Complete output from command c:\users\dr_success\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;**file**='C:\Users\DR_SUC~1\AppData\Local\Temp\pip-build-u0318qv4\dukpy\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\DR_SUC~1\AppData\Local\Temp\pip-l_n4e21_-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\dukpy
    copying dukpy\babel.py -> build\lib.win-amd64-3.5\dukpy
    copying dukpy\coffee.py -> build\lib.win-amd64-3.5\dukpy
    copying dukpy\evaljs.py -> build\lib.win-amd64-3.5\dukpy
    copying dukpy\install.py -> build\lib.win-amd64-3.5\dukpy
    copying dukpy\module_loader.py -> build\lib.win-amd64-3.5\dukpy
    copying dukpy\tsc.py -> build\lib.win-amd64-3.5\dukpy
    copying dukpy__init__.py -> build\lib.win-amd64-3.5\dukpy
    creating build\lib.win-amd64-3.5\dukpy\webassets
    copying dukpy\webassets\babelfilter.py -> build\lib.win-amd64-3.5\dukpy\webassets
    copying dukpy\webassets\typescriptfilter.py -> build\lib.win-amd64-3.5\dukpy\webassets
    copying dukpy\webassets__init__.py -> build\lib.win-amd64-3.5\dukpy\webassets
    creating build\lib.win-amd64-3.5\dukpy\jsmodules
    copying dukpy\jsmodules\babel-6.4.4.min.js -> build\lib.win-amd64-3.5\dukpy\jsmodules
    copying dukpy\jsmodules\coffeescript.js -> build\lib.win-amd64-3.5\dukpy\jsmodules
    copying dukpy\jsmodules\semver.js -> build\lib.win-amd64-3.5\dukpy\jsmodules
    copying dukpy\jsmodules\typescriptServices.js -> build\lib.win-amd64-3.5\dukpy\jsmodules
    creating build\lib.win-amd64-3.5\dukpy\jsmodules\react
    copying dukpy\jsmodules\react\react-dom-server.js -> build\lib.win-amd64-3.5\dukpy\jsmodules\react
    copying dukpy\jsmodules\react\react.js -> build\lib.win-amd64-3.5\dukpy\jsmodules\react
    running build_ext
    building 'dukpy._dukpy' extension
    error: Unable to find vcvarsall.bat

**Comment by azazel75** [comment]
probably it's the compilation of the javascript engine of duckpy, which is written in c/c++. Unfortunately i do not have a Windows installation to try it on and so i cannot support you on this. Anyway it seems to be a duckpy bug.
