### ISSUE TITLE
raised asserterror when Inherit a object attribute

### ISSUE THREAD

**Issue by RyanKung** [azazel75/metapensiero.pj#17]
works on

```
from react import React

Component = React.Component


class MeasureList(Component):
    def CommponentWillMount(self):
        pass
```

but not works with

```
from react import React


class MeasureList(React.Component):
    def CommponentWillMount(self):
        pass
```

**Comment by azazel75** [comment]
Yes, there is a check that enforces the superclass to be a Name, but there is no such need for it... I think i'll relax it. 

@RyanKung can you try JavaScripthon from the github repositotydirectly?

**Comment by azazel75** [comment]
@RyanKung if you have questions other than bugs, you can join the chat on gitter at https://gitter.im/javascripthon/Lobby and ask there
