### ISSUE TITLE
Consider embedded compiler

### ISSUE THREAD

**Issue by icarito** [azazel75/metapensiero.pj#22]
Compiling on the client side would be nice.

My use case is building an IDE.

I'm also looking at:
https://github.com/pybee/batavia/issues/294

Currently it seems I'm limited to Rapydscript, Skulpt or Brython.
Comments welcome.

Thanks!

**Comment by azazel75** [comment]
Hi Sebastian, 

compiling on the client would mean replacing all the parts of the Python's standard library that JavaScripthon is using to parse the source code with something that runs on JavaScript, just to name the first thing that comes to mind.  That's a lot of work  and frankly I don't have so much interest in it, but I'm happy to accept  contributions :-)

**Comment by icarito** [comment]
Thanks for your answer! I'm still a bit new but your answer helps assess the project. As I learn, perhaps sometime it will be feasible!
