### ISSUE TITLE
i installed dukpy & javascripthon successfully but when i call pj it show me that error win7 sp1 64bit

### ISSUE THREAD

**Issue by SLADE93** [azazel75/metapensiero.pj#24]
Traceback (most recent call last):
  File "C:\Python27\Scripts\pj-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3017, in
<module>
    @_call_aside
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3003, in
_call_aside
    f(*args, **kwargs)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 3030, in
_initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 659, in _
build_master
    ws.require(__requires__)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 967, in r
equire
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 853, in r
esolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dukpy' distribution was not found and i
s required by javascripthon

**Comment by SLADE93** [comment]
to be mentioned  i faced errors while installing dukpy  -> "src_support.c(1): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
error: Setup script exited with error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2"

but i solved that problem
I created unistd.h from the most popular answer here
http://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c

and downloaded getopt.h and getopt.c from here
http://www.codeproject.com/Articles/157001/Full-getopt-Port-for-Unicode-and-Multibyte-Microso

and I put them into C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\

after that an error showed up to me "c:\users\batman\anaconda3\envs\py35\include\pyconfig.h(193): error C2632: '__int
64' followed by 'int' is illegal
c:\users\batman\anaconda3\envs\py35\include\pyconfig.h(193): warning C4091: 'typ
edef ': ignored on left of '__int64' when no variable is declared"

I changed line 193 in py35\include\pyconfig to typedef signed __int64 int64_t;

**Comment by azazel75** [comment]
hi @SLADE93, It seems to me that despite your efforts to compile dukpy, it isn't installed correctly yet. Unfortunately I cannot support Windows directly because compiling on it is a pain in the ass. You should ask to the dukpy mainainer if he can help you out
