### ISSUE TITLE
Support for int( ) and float( )?

### ISSUE THREAD

**Issue by techninja** [azazel75/metapensiero.pj#30]
Seems silly, but when converting this simply stops on these standard and common inbuilt math functions saying `Name 'int' is reserved in JavaScript `. Perhaps should simply be `parseInt()` and `parseFloat()`?

**Comment by azazel75** [comment]
Hi, 

thanks for using javascripthon! Could you plise write an example of your python code?

**Comment by techninja** [comment]
Thanks for making it!

```python
test1 = int(round(a + b))
```

I can get this to make the following error:
```
UnsupportedSyntaxError: Node type 'Name': Line: 1, column: 8. Name 'int' is reserved in JavaScript.
```

**Comment by azazel75** [comment]
Uh you are right, I never used it

**Comment by techninja** [comment]
Really, what I'm trying to do is convert parts of the [linear acceleration code found here](https://github.com/evil-mad/axidraw/blob/master/inkscape%20driver/axidraw.py) into something _close_ and I can convert the rest by hand. I'll be adapting my own libraries and includes, I just need something to automate a lot of the conversion and save time.

**Comment by azazel75** [comment]
Hey @techninja, let me know ho it works, I've closed it but feel free to reopen it if isn't working properly.

About the code you are converting, keep in mind that equalness comparison in Python and JS are two very different concepts and that JavaScripthon always converts equal comparison to JS strict comparison (===).. Unfortuately the only way to presereve the sam behaviour would be to implement recursive equalness comparison of complex objects on the JS side, but is not there now.
