### ISSUE TITLE
What is the license of transpiled code?

### ISSUE THREAD

**Issue by pombredanne** [azazel75/metapensiero.pj#31]
Hi: for the sake of clarity, do you assert a GPL license on the translated code? An does it need any GPL-licensed runtime library of yours at runtime?
Thanks!

**Comment by azazel75** [comment]
Hi @pombredanne,

really, the only `runtime library`  that exists are the contents of the https://github.com/azazel75/metapensiero.pj/blob/master/src/metapensiero/pj/snippets.py and even if it has the same license as the rest of the code, I never thought of stating any license about its translated product that gets added (sometimes) to the translated code.

You can distribute any product of JavaScripthon with the license you prefer. I'll remember to state this more clearly on the docs and the license file.

About the runtime, or the lack of thereof, I  plan to give JavaScripthon a sort of "layered" translation system that will enable the use of libraries like underscore or lo-dash to do the hard work, so I don't think that the runtime as it is now will grow in the future.

Is it clear?

**Comment by pombredanne** [comment]
@azazel75 Thanks .... crystal clear. This would be a great addition to the doc
