### ISSUE TITLE
`float` is a reserve word in javascript error

### ISSUE THREAD

**Issue by robertleeplummerjr** [azazel75/metapensiero.pj#32]
I ran: `python3.6 -m metapensiero.pj basic.py` on
https://github.com/OpenMined/PySyft/blob/a127e7155788be4fbff72d234060fb1432ab560d/syft/he/paillier/basic.py

and got `An error occurred while compiling source file 'basic.py'
UnsupportedSyntaxError: Node type 'Name': Line: 66, column: 63. Name 'float' is reserved in JavaScript.`

Which references: https://github.com/OpenMined/PySyft/blob/a127e7155788be4fbff72d234060fb1432ab560d/syft/he/paillier/basic.py#L66

I believe since there is: https://docs.python.org/3/library/functions.html#float what we'd actually want to output from the parser is `Number.parseFloat(tensor)`

Can we have this support added?

**Comment by azazel75** [comment]
Hi @robertleeplummerjr, and thanks for giving JavaScripthon a try and reporting this. This is filxed already in master, although I haven't made a new release

```
$ pj -s - 
float('1.5') 

parseFloat("1.5");
```

Can you try the code from this repo and install it with `pip -e` and report back if it works for you?

thanks 

P.S. you should be aware that JavaScripthon will not convert those __mul__ methods to anything meaningful.

**Comment by azazel75** [comment]
the same can said for the __add__ and __sub__ methods

**Comment by robertleeplummerjr** [comment]
1. Is there anything holding up a release?
2. Do you have a recommendation regarding add and sub methods?

**Comment by azazel75** [comment]
>>>>> "Robert" == Robert Plummer <notifications@github.com> writes:

    Robert> 1. Is there anything holding up a release?

yes, I've added a new dependency in master which is unreleased as well (
https://github.com/azazel75/macropy ) and as of now needs to be
installed using `requirements.txt` file to install it directly from the
repo.

As of now I'm unsure if i'll keep it.... I'm trying out some new
approach to match the transformation routines to the AST

    Robert> 2. Do you have a recommendation regarding add and sub methods?

What the behavior you expect from your converted code? Those methods are
there so that when in the code there is an expression like `a + b` and
the class of `a` has one of those methods defined the addition will be
controlled by that defined method.

Now, there's no similar feature in JS, even in ES7 JS, so it's very
hard to implement, probably it's much simpler to get it working in
python-in-js interpreters like brython or skulpt, also it seems that
transcrypt has some support for operator overloading,
http://www.transcrypt.org/docs/html/special_facilities.html?highlight=__add__#operator-overloading-pragma-opov-and-pragma-noopov

**Comment by robertleeplummerjr** [comment]
Is there a way we can get the commits that fix the float issue, and get that released, so that we benefit from the bug fixes?  Thank you for the pointers!

**Comment by azazel75** [comment]
I'll try to find the time to do a release

**Comment by azazel75** [comment]
@robertleeplummerjr  I've released version 0.7, please give a it a try and let me know

**Comment by robertleeplummerjr** [comment]
huzzah!

**Comment by azazel75** [comment]
@robertleeplummerjr does it works?

**Comment by robertleeplummerjr** [comment]
I'll test it momentarily.

**Comment by robertleeplummerjr** [comment]
Now when I install, I get:
```
Collecting javascripthon
  Downloading javascripthon-0.7.tar.gz (530kB)
    100% |████████████████████████████████| 532kB 2.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vv/n8mynbmn21s9nbh42681klydgfn2lt/T/pip-build-VZZDT6/javascripthon/setup.py", line 14, in <module>
        with open(os.path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by azazel75** [comment]
How strange! What python version are you using?

**Comment by robertleeplummerjr** [comment]
I am on osx, so I have both 2.7.13, and 3.6.2.  My alias is to call from 3.6.2 though, but not sure if pip is using that, or fighting it.

**Comment by azazel75** [comment]
most certainly it isn't

**Comment by robertleeplummerjr** [comment]
`python3 -m pip install javascripthon --no-cache-dir` seems to have done the trick

**Comment by robertleeplummerjr** [comment]
That uses the older version, which isn't yet released.  If I install from source, the step `$ pip install -r metapensiero.pj/requirements.txt` gives me: `You must give at least one requirement to install (see "pip help install")`

**Comment by robertleeplummerjr** [comment]
Note: I actually used `python3 -m pip install -r metapensiero.pj/requirements.txt`

**Comment by azazel75** [comment]
there's non need for this last step... just install `python3 -m pip install javascripthon==0.7`

**Comment by robertleeplummerjr** [comment]
That did it!
