### ISSUE TITLE
else if

### ISSUE THREAD

**Issue by danielkop** [azazel75/metapensiero.pj#5]
Readme shows this for if elif else..
if ((foo > 0)) {
    ....
} else {
    if ((foo < 0)) {
        ....
    } else {
        ....
    }
}

Personally i prefer the "else if" style instead:
if {
....
}
else if {
...}
else if {
...
}
else {
..
}

**Comment by azazel75** [comment]
I concur! But the current implementation is simpler, but i like having a nice syntax ;-)

**Comment by lelit** [comment]
@azazel75, I'm sorry but I think it would be better to revert the change, as it is suboptimal because it produces an ugly indentation:
```python
def func():
    a = 1
    if True:
        if a == 0:
            window.alert("Can't be")
        elif a < 0:
            window.alert("Something's wrong")
        else:
            window.alert("That's it")
```
produces:
```javascript
var a;
a = 1;
if (true) {
    if ((a === 0)) {
        window.alert("Can't be");
    } else if ((a < 0)) {
    window.alert("Something's wrong");
} else {
    window.alert("That's it");
}

}
```
 I will try to fix that, but from my first quick experiments it requires fiddling with the indentation logic that I'm not sure if it's worth the hassle
