### ISSUE TITLE
range()

### ISSUE THREAD

**Issue by danielkop** [azazel75/metapensiero.pj#6]
Range can have a start, end and step value.
It can be for i in range(5,10):
but it can also be for i in range(10,5,-1):

In that case you would want change the third part of the loop to i += step, instead of i++.

**Comment by azazel75** [comment]
Good catch, thanks... i rarely use it but it's rather simple to implement

**Comment by azazel75** [comment]
Implemented in https://github.com/azazel75/metapensiero.pj/commit/3b12fd94c211974beca14d0c174cb1f4f5c1f1eb ,
