### ISSUE TITLE
Awesome project, want to contribute

### ISSUE THREAD

**Issue by ironmaniiith** [azazel75/metapensiero.pj#8]
Hello @azazel75 
You have done a great work man, really I mean it. This is an awesome project and I liked it so much. :smile: 
I want to start contributing to this project, are there any particular contributing guidelines, if not what are the highest priorities that need to be solved or added for now, I can help you out with those.

Thanks.

**Comment by azazel75** [comment]
Hi @ironmaniiith,

there are some TODO points in the readme, or even the issue #6 is quite simple to fix. Feel free to pick what you like.

The guidelines are to follow PEP8 for coding where possible, so use CamelCase for classes and snake_case for variables, functions and members, and UPPERCASE for constants. Try to keep lines lengths under 79 chars, more or less ;-)

The workflow is to fork the project, d your stuff, maybe add a test for it and then  submit a pull request.

Have fun

**Comment by ironmaniiith** [comment]
Thanks @azazel75 :+1:

**Comment by azazel75** [comment]
@ironmaniiith,  have a look at the readme

**Comment by ironmaniiith** [comment]
Just a minor typo #10
